# Generated by Django 3.2 on 2023-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msfhistory',
            name='job_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='msfhistory',
            name='type',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='device_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='hostname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='ipv6',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='mac',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='os',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='vendor',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhostdetails',
            name='version',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
